### ISSUE TITLE
Finalize instructional information for authors on how to use this material

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/article_templates#1]
@mrshirts - I think I volunteered to curate the GitHub side of things. Any thoughts on what I should be doing on here? Things that come to mind offhand are:

Basic repo:
- [x] Make sure there are good README's explaining what this is about, linking to journal, etc.
- [x] Make sure there are examples of using the template (the template itself provides one; we can add more later)

In a new "paper writing as code development" document:
- [x] Likewise give some brief explanations of "paper-writing as code development" and why

In some instructional documents (here or somewhere else? Update: I like here for things which should get attached to their repo, which will be quite a few of these), deal with GitHub practicalities for authors:
- [x] Explain how authors should set up their GitHub repo (protecting master, enabling issue tracker, etc.)
- [x] Explain how to handle versioning and dates of changes
- [x] Explain how to do a release
- [x] Explain the branch-pull-merge/fork-pull-merge models
- [x] Have them protect master 
- [x] Give LaTeX formatting tips for easier handling of revisions on GitHub (e.g. one sentence per line)
- [x] Give concrete examples of specific scenarios and handling via GitHub

What else am I missing?

I've added several of the above in ~#1~ (some PR, not that one).

**Comment by mrshirts** [comment]
Updated a bit in #8

**Comment by davidlmobley** [comment]
Closed by #42
