### ISSUE TITLE
Make this a "fork this repo to start your article" repo?

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/article_templates#11]
I wonder if we should reorganize this a bit into something which authors can just fork in order to immediately start their GitHub repos. Probably that was the intention and it didn't dawn on me until now. For some reason I had in my head the main thing they'd be getting was the LaTeX stuff.

I think if we were going to reorganize that way, we would make sure to have NO information here about how to do things (e.g. the README.md content relating to the issue tracker, etc.) and just provide templates they should update for everything:
- Template LaTeX
- Template README.md for their article, including info on what this publication model is, etc.
- Template "instructions for readers/commenters" md file for them to edit which has boilerplate text on how readers can raise issues, etc.

Anything else?

**Comment by mrshirts** [comment]
That makes a  lot of sense. We can have one class file, and then .tex files for each of the article types: they can choose the one they want and delete the others.  Alternatively, we could have a separate repository for each article type, though that seems like overduplication.

> Template README.md for their article, including info on what this publication model is, etc.

Not quite sure what you mean by "their article".  You mean, a README.md for their type of article?  Or that they will turn into the README.md for their article?

If this is intended as a forked repository, then we don't need "About the journal".  It seems like it the other stuff "LaTeX and GitHub" may be useul.

Maybe we keep that as the `README.md`, and make a `your.README.md` file that says "when you release your repository, delete our "README.md" and move `your.README.md` to `README.md`. 

Or we could put the information currently here somewhere else, but

**Comment by davidlmobley** [comment]
> That makes a lot of sense. We can have one class file, and then .tex files for each of the article types: they can choose the one they want and delete the others.

Yes, absolutely. Especially if we put in placeholders for the different elements we think are important (glossary, checklist, etc.) this will go a long way towards making the instructions unnecessary. 

Our instructions for using these can say "fork and then delete the tex files for the other article types" or some such.

> Not quite sure what you mean by "their article". You mean, a README.md for their type of article? Or that they will turn into the README.md for their article?

A README.md that they will turn into the README.md for their article. Naively, it seems like you would want to have some introductory material which explains a bit about how contributions from the community are welcomed, etc. The authors would probably be free to add or change this -- but just providing some boilerplate that explains the basic idea in case they want to just use it as is.

> If this is intended as a forked repository, then we don't need "About the journal". It seems like it the other stuff "LaTeX and GitHub" may be useul.

Maybe, except if we have the other stuff in the repo they are going to fork, then there will be a copy of it in EVERY repo unless people remove them, which may make it unclear if (a) you want to update the source file where you should do it, and (b) which version of these will be most up to date. Simpler might be just to make sure the template README.md file has boilerplate that links to the authoritative versions of these.

> Maybe we keep that as the README.md, and make a your.README.md file that says "when you release your repository, delete our "README.md" and move your.README.md to README.md.

That would work! This seems like the best idea. 

> Or we could put the information currently here somewhere else, but I think it sort of belongs with it? It's the instructions on how to use it.

Yes, probably that's exactly what we should do -- keep our README.md and make a file they will replace this with once they have forked. We could also have an "instructions_for_authors.md" which says exactly how to do this if we like (so they don't lose it when they move their file onto README.md).

**Comment by mrshirts** [comment]
Mostly addressed in in https://github.com/livecomsjournal/article_templates/pull/12

**Comment by mrshirts** [comment]
I think we've clarified this?
