### ISSUE TITLE
Alter citation format

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/article_templates#25]
Currently, the citation format is the (FirstAuthorSurname (Year)) format. This 1) adds bloat to the articles and 2) unnecessarily complicates cross-referencing the in-text citation to its associated entry in the bibliography.

I suggest that the citation format be altered to the physics-style numbered format, e.g., "For example, Leach’s Molecular Modelling [2] ..." instead of "For example, Leach’s Molecular Modelling (Leach(2001)) ..."

**Comment by davidlmobley** [comment]
Totally agree; I think we discussed it somewhere and this change just didn't make it in yet. Maybe with @hmayes ? 

Is there anything else we should be changing at the same time, e.g., layout of info within citations?

**Comment by dwsideriusNIST** [comment]
For the bibliography layout, we need to decide if DOI and/or title is required in the entry or not.

I'd be happy if we adopted a standard format, like Phys Rev or J Chem Phys. They are compact but sufficiently verbose.

**Comment by davidlmobley** [comment]
We have no length limits, so I think we should have title for sure. DOI makes sense to me too since we'll want to encourage citation of non-traditional publications which may have DOIs.

**Comment by dwsideriusNIST** [comment]
Good point about no length limit; if DOI is required (when it exists) then we should add that to the author guide.

**Comment by mrshirts** [comment]
I agree about adding instructions to add DOI.  I will play around with the bibliography style.

**Comment by jchodera** [comment]
I think hyperlinked DOIs are a great idea. The current eLife template makes them appear in nice hyperlinked form in the manuscript, but some more tweaking would be needed to make sure `http://doi.org/` is prepended to the `doi` field content to get the link to work correctly.

**Comment by mrshirts** [comment]
One thing I remembered with natbib is that if you have numbered citations, then the \citep{} notation fails.  This takes a bit of a workaround that I haven't figure out yet.

**Comment by mrshirts** [comment]
Also, do people prefer square bracket numbers, or superscripts?  I'm leaning towards square brackets.

**Comment by dwsideriusNIST** [comment]
I vote for square brackets; you can just use \cite{} everywhere instead of the menagerie of \cite, \onlinecite, \citen depending on the sentence structure.

**Comment by hmayes** [comment]
That is a huge plus!!

**Comment by davidlmobley** [comment]
Agreed with square brackets, yes.

**Comment by davidlmobley** [comment]
@dwsideriusNIST - are you doing this or do you need us to work on this?

**Comment by dwsideriusNIST** [comment]
Sorry, I thought we had someone specifically handling the class file modifications.

I won't be able to work on it for a week or so, so if someone else wants to attempt it before then, please go ahead!

**Comment by davidlmobley** [comment]
I think changing the citation style is just something which is done with options in the TeX of the template, and not the class file. :)

**Comment by dwsideriusNIST** [comment]
In that case, we need a list of built-in class options in the author guide.

**Comment by mrshirts** [comment]
I'll take it, might take a couple of days to get to.

**Comment by dwsideriusNIST** [comment]
I found the instructions in the livecoms.cls file that are controlling the citation style. If we want to make that an option for the class, then it will involve deeper modifications to the class file. A pull-request will be sent in momentarily.

**Comment by dwsideriusNIST** [comment]
While working on the reference format, I also considered changing the color of the citations; currently they are "LiveCoMSMediumGrey" - which doesn't stand out well.

Would a few of you look at the bracketed citation style and let me know if you think a different color would be better? I know exactly where to make the modification in the class file.

To see an example, clone this repo: https://github.com/dwsideriusNIST/article_templates and checkout the "citation_color" branch to see a version that uses "LiveCoMSLightBlue" instead of grey.

**Comment by davidlmobley** [comment]
Do you mind pushing an example PDF which has that color in it? I visited the PDF in your branch on GitHub but I'm not finidng a citation in this color in it. (Or maybe it's there and I'm not looking on the write page...)

**Comment by dwsideriusNIST** [comment]
An updated PDF is now in the "citation_color" branch of https://github.com/dwsideriusNIST/article_templates

Look on page 6, first column, first paragraph, for an example.

**Comment by davidlmobley** [comment]
I like that a lot. @hmayes , thoughts?

For a direct link, use https://github.com/dwsideriusNIST/article_templates/blob/citation_color/templates/livecoms-template-bestpractices.pdf

Thanks.

**Comment by hmayes** [comment]
I'm a fan of blue, so I like it!

**Comment by davidlmobley** [comment]
Resolved by #36 .

**Comment by dwsideriusNIST** [comment]
I'm reusing this issue thread instead of creating a new one.

Do we want to impose strict formatting of the URL / DOI in the bibliography? I'm finalizing the references for the sampling uncertainty paper and need to make a decision one way or the other.

Using the "url" tag in BibTeX creates a nice link. But I would highly recommend requiring the URL to be "https://dx.doi.org/10.XXXX/YYYYY" as opposed to the publisher's proprietary link (which will change). 

Conversey, using the "doi" tag in BibTeX creates a doi entry in the reference, but it is not a hyperlink that actually works (for any of the PDF viewers I've tested it with).

"doi" seems to be a better choice from a citation / reference cataloging POV, but the link is useless. Using both seems duplicative.

Thoughts?
