### ISSUE TITLE
Issue compiling the new template

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/article_templates#26]
Compiling the new template, I have two issues, that are probably resolvable for me, but might be problematic for new people by raising the barrier.  Should we check with LianTze on this?

1) if attempting to compile with 'pdflatex', I get 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Fatal fontspec error: "cannot-use-pdftex"
! 
! The fontspec package requires either XeTeX or LuaTeX to function.
! 
! You must change your typesetting engine to, e.g., "xelatex" or "lualatex"
! instead of plain "latex" or "pdflatex".
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

Some people might not want to/be able to switch?  Both programs seem to be installed in my LiveTeX distribution, though. We need to check on portability on this, though. 

2) If I switch to 'xelatex', I get the error:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "Latin Modern Mono" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.74 ...t[Scale=MatchLowercase]{Latin Modern Mono}
                                                  
? H
|'''''''''''''''''''''''''''''''''''''''''''''''
| A font might not be found for many reasons.
| Check the spelling, where the font is installed etc. etc.
| 
| When in doubt, ask someone for help!
|...............................................

When I switch to 'lualatex', it spends a while building a font database, then I got several errors of the form 

! LaTeX Error: Command `\digamma' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.259 ...mbol{\digamma}        {\mathord}{AMSb}{"7A}
                                                  
? 

! LaTeX Error: Command `\backepsilon' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.265 ...mbol{\backepsilon}    {\mathrel}{AMSb}{"7F}

With a few more weird warnings scattered in.

**Comment by davidlmobley** [comment]
Checking in with her sounds fine to me.

**Comment by mrshirts** [comment]
To be more specific on what didn't work: running pdflatex --version on the binary that had the issues above, I got:

pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)
kpathsea version 6.2.1
Copyright 2015 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.17; using libpng 1.6.17
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.04

**Comment by liantze** [comment]
Compiling the template with pdflatex was fine for me—in fact I made the assumption authors would mainly be using pdflatex. (I tested with TeX Live 2016 and 2017; I don't have TL2015 though, but many packages in TL2015 are a bit outdated.)

There _is_ some problem with XeLaTeX and LuaLaTeX in TL2016/2017 though; mainly over math font clashes. I'll see if I can fix that later today.

**Comment by mrshirts** [comment]
I can now compile with XeLaTeX.

**Comment by davidlmobley** [comment]
@mrshirts no problem with giving those instructions. You'll add?

**Comment by davidlmobley** [comment]
cc #30 - @dwsideriusNIST needed these instructions. :)

**Comment by davidlmobley** [comment]
Opened a PR to resolve this by documenting LaTeX needs; marking as closed.
