### ISSUE TITLE
Text width - wasted space on pages =/= 1

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/article_templates#27]
One more stylistic concern: the elife template uses a very wide left margin; I suspect this is to provide the "For correspondence", etc. text blocks on the first page. But on every other page, this is just wasted space. Can we modify the class file to use more of the page width for pages 2+?

**Comment by mrshirts** [comment]
Are you looking at the most up to date version?  I see a left margin that is slightly larger than the right, but not by much; like 0.5 inch on the right and 0.75 on the left.

**Comment by dwsideriusNIST** [comment]
Mea culpa, the class file for our repo was out of date. It looks fine when recompiled with the updated version.
