### ISSUE TITLE
LaTeX class - section names in header

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/article_templates#30]
I suggest that the LaTeX class be modified to remove the section and subsection names in the header of each page. It's inconsistent and uses numbering that is not in the actual text.
![screenshot_2017-10-25](https://user-images.githubusercontent.com/5341350/32002908-98593106-b96b-11e7-9764-95e4287f2707.png)

**Comment by davidlmobley** [comment]
@dwsideriusNIST - yes, I agree that needs changing. You're also getting close to having a collision between the two. Not good.

Is it better to remove them entirely, or to retain the header for the section? 

@hmayes @dmzuckerman any thoughts?

**Comment by dmzuckerman** [comment]
We certainly don't want a collision, but I don't see any problem with a section header - I suspect subsection names will be too specialized and lack context.

BTW perhaps @dwsideriusNIST hasn't used the very latest template, which I thought did include section numbers.

**Comment by dwsideriusNIST** [comment]
@dmzuckerman I just re-pulled the livecoms.cls to double check and there are no section numbers after I recompile. A quick check of livecoms.cls didn't find a class option to show/remove the section headers.

I would vote for dropping everything from the header.

If there is a consensus around keeping some of the header, then my preference is:
1) drop subsection
2) drop numbering (perhaps scratch this given the above)
3) have the section header refer to the section at the top of the page. At present, it shows max(current_section,first_new_section_on_page). The header could refer to a section that is nearly at the bottom of the page.

**Comment by davidlmobley** [comment]
@dwsideriusNIST -- this is very strange. I'm not seeing any kind of headers at all when I'm processing the `livecoms-template-bestpractices.tex` using the current class file in the repo (see screenshot). Can you give a link to your repo where you are doing this? Your document looks rather different from how I'm expecting, as it does NOT have the section numbers in the main text (as it should) and DOES have a header with section numbers/headings (as it shouldn't).  So I'm very confused.

![livecoms-template-bestpractices_pdf](https://user-images.githubusercontent.com/7132257/32010305-4d2fcd34-b966-11e7-9637-2a84032972b1.jpg)

**Comment by davidlmobley** [comment]
@dwsideriusNIST - maybe you're running into some kind of GitHub issue where you are not actually getting the latest livecoms.cls from THIS repository, and are instead just using one from a fork or a new repo you are working from for your paper?

**Comment by dwsideriusNIST** [comment]
I'll re-check the repos. For the moment, you can check this paper: https://github.com/dmzuckerman/Sampling-Uncertainty

Maybe it's related to the TeXLive distro I'm using? I'll get back to this thread shortly.

**Comment by dwsideriusNIST** [comment]
OK, there's a few different issues:

1. The Sampling-Uncertainty paper did not specify the "bestpractices" class options. With that, the headers are like your example.
    -> Means we need to either clean up the situation where no document type is specified OR require that a document type be specified.
2. I'm still not getting the section numbers. I re-cloned this repo, then compiled livecoms-template-bestpractices.tex and here's the result:

![screenshot_2017-10-25-2](https://user-images.githubusercontent.com/5341350/32011064-ac18e874-b981-11e7-86bc-3baf38409659.png)

FYI, I'm using TeX Live in Ubuntu (pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian))

I'll test this on a Mac and see if there's a difference.

**Comment by davidlmobley** [comment]
@dwsideriusNIST - @mrshirts noted a requirement (which we will need to get into the documentation) for TL2016 or equivalent, so you need to update your TeX Live -- see https://github.com/livecomsjournal/article_templates/issues/26#issuecomment-337787068

**Comment by dwsideriusNIST** [comment]
Well, my Mac reproduces your PDF exactly. It runs Tex Live 2016, so that has to be the problem.

That said.... it would be good to track down *where* this is creeping in. Probably the livecoms.cls file is referencing something else and the 2015 vs. 2016 versions are a bit different.
