### ISSUE TITLE
Clean up behavior when no document type class option is specified or require its specificiation

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/article_templates#33]
Currently, we don't get the desired format when a class option (such as `bestpractices`) is not specified (see https://github.com/livecomsjournal/article_templates/issues/30#issuecomment-339393621 ) ; we either need to make sure it still formats properly in such cases OR require a document type class option be specified. I'd lean towards the latter.

@liantze - is one of these easier/better than the other? Are you able to help with this?

**Comment by liantze** [comment]
It looks like the page headers are controlled by `\ifdocumenttype`, so perhaps the easiest thing to do would be to move `\fancyhf{}` out of the conditional, so that the running headers is cleared and blank if no document type is specified?

**Comment by davidlmobley** [comment]
Sounds great, @liantze .
