### ISSUE TITLE
Possible issue when using lualatex

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/article_templates#43]
Something goes wrong with the inclusion of the github repo name in the front matter, so that it extends into the abstract, using luauatex from TexLive 2015.  The solution may simply to be not recommend lualatex, since most people don't use it anyway. This does not appear to be a problem with latex from TexLive 2016 or later.

<img width="377" alt="bad_repo" src="https://user-images.githubusercontent.com/4274132/33240716-db41b234-d277-11e7-81dd-d60c763f2249.png">

**Comment by davidlmobley** [comment]
There previously was a thread that indicated you had problems with this version. One of my recent PRs adds a note that you need the 2016 version or later to use our templates.

**Comment by davidlmobley** [comment]
Marking as closed for now.
