### ISSUE TITLE
GitHub repo URLs split across multiple lines

### ISSUE THREAD

**Issue by jchodera** [livecomsjournal/article_templates#46]
The current template puts the "blurb" containing the GitHub repo URL in a special left text box, which causes it to split awkwardly across multiple lines:
![image](https://user-images.githubusercontent.com/3656088/33520996-a7d24a5a-d793-11e7-91af-6a4ee8a19d34.png)
Instead, what if we eliminate the left-hand text and put this just under the Abstract?
![image](https://user-images.githubusercontent.com/3656088/33521044-d7ff40d8-d794-11e7-9656-5c9d331277df.png)
I can open a PR if people like this style.

**Comment by davidlmobley** [comment]
I think we like the lefthand blurb (at least, we deliberated about this and decided to put it there); the link still works and it makes it stand out that this is something special. It's easily lost/ignored under the abstract.

**Comment by jchodera** [comment]
Here's a better way to make it stand out:
![image](https://user-images.githubusercontent.com/3656088/33522604-9e6bb9a8-d7be-11e7-86d6-454290963033.png)

**Comment by davidlmobley** [comment]
I think we settled on the lefthand side blurb fairly firmly, so I will mark this as closed but can reopen if design-oriented folks (@dwsideriusNIST ? @hmayes ?) think otherwise.
