### ISSUE TITLE
Fix text justification for figure captions, table captions, and abstract

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/article_templates#47]
New issue, visible in main.pdf of https://github.com/dmzuckerman/Sampling-Uncertainty/commit/35d18d5fe86e78b305f2c6b995e18cb5ec389fa6

Figure captions are right justified, when they should be full justified.

**Comment by dwsideriusNIST** [comment]
Additional note: this does not affect table captions.

**Comment by dwsideriusNIST** [comment]
Affects tables too. Potential fix identified.

**Comment by dwsideriusNIST** [comment]
See PR https://github.com/livecomsjournal/article_templates/pull/48

Also, may consider applying the same justification to the abstract.

**Comment by davidlmobley** [comment]
Good catch, @dwsideriusNIST . I had not caught this. 

I'll merge the PR. Should we also get the abstract in a separate PR? You'll handle?

**Comment by dwsideriusNIST** [comment]
See PR #49

**Comment by dwsideriusNIST** [comment]
\Raggedright affects the author affiliation block as well. I've tried a few changes to livecomes.cls, but wasn't able to change it to full justification.

**Comment by davidlmobley** [comment]
Just to be clear, @dwsideriusNIST - are you worried about making the author block be justified, or worried you have messed it up by making changes to the rest?

**Comment by dwsideriusNIST** [comment]
First question is whether the author affiliation block should be full justified or not; it currently is \raggedright.

Then there's the question of how to fix it. There is a command "Affilfont" on line 311 of the livecoms.cls file, but removing \raggedright does not change the justification (I was able to change the font style of the affiliation block with that line), so I suspect that the \raggedright condition is coming from the parent class.

**Comment by davidlmobley** [comment]
I wouldn't worry about the author block not being justified, personally.

**Comment by dwsideriusNIST** [comment]
I have no problem leaving it raggedright. Closed.
