### ISSUE TITLE
Section / subsection titles intruding into gutter and margins

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/article_templates#50]
New formatting issue: long section and subsection titles intrude into the gutter between columns and the right margin. For example, see page 7 of https://github.com/dmzuckerman/Sampling-Uncertainty/blob/4bf625d64a533da9e20aab0ddb625e711c2e56d3/main.pdf

**Comment by davidlmobley** [comment]
@liantze are you able to help with this?

I've also had an issue where bibliography entries do not sort & compress properly with natbib (despite this being in the class file); is that something you are running into as well, @dwsideriusNIST ?

**Comment by dwsideriusNIST** [comment]
@davidlmobley No I've not noticed any sorting problems. (pdflatex does "pause" for an unexpected amount of time when it gets to .../natmove.sty, but ultimately it does compile.) Can you point me to an example?

**Comment by davidlmobley** [comment]
In your PDF linked to above, references are in alphabetical not numerical order. I thought they were supposed to be in numerical if correctly sorted/compressed?

**Comment by dwsideriusNIST** [comment]
Closed issue #25 didn't address the alphabetical vs. numerical order question; I thought the alphabetical ordering was chosen purposely. I would vote for numerical order by appearance, though.

**Comment by davidlmobley** [comment]
Likewise.

**Comment by dwsideriusNIST** [comment]
References issues are now in #51

**Comment by liantze** [comment]
It looks like LaTeX is somehow trying too hard to fit hyphenated words into the sectional headings and failing. It's probably cleaner to just left-align the sectional headers and not attempt to justify on both ends? This is included in #52 .

**Comment by davidlmobley** [comment]
@dwsideriusNIST - doublecheck that this is fixed now that #52 is merged? (Thanks @liantze !)

**Comment by dwsideriusNIST** [comment]
This fix works for the sampling uncertainty paper.
