### ISSUE TITLE
Number references by order of appearance

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/article_templates#51]
References should be numbered by order of appearance in text, e.g. not as in https://github.com/dmzuckerman/Sampling-Uncertainty/blob/4bf625d64a533da9e20aab0ddb625e711c2e56d3/main.pdf

**Comment by dwsideriusNIST** [comment]
I took a quick look at this and didn't find an obvious problem. Natbib by default does not sort the references in order of appearance, so the BST file has to be modified. So far my quick mods have not changed the situation.

**Comment by mrshirts** [comment]
I generally know how to do these sorts of things, with a little time.  You can assign it to me if nobody else knows right off.  Might take a few days to get to, though.

**Comment by liantze** [comment]
eLife wanted to use Vancouver but as author-year, so that .bst sorts the reference list by authors. I've submitted PR #52 to remove this sorting, with an additional `\cite` in `sample-document.tex` that would make this easier to check.

**Comment by davidlmobley** [comment]
Closed by #52 .
