### ISSUE TITLE
Reference standards for bibliography.

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/article_templates#53]
Do we want to impose strict formatting of the URL / DOI in the bibliography? I'm finalizing the references for the sampling uncertainty paper and need to make a decision one way or the other.

Using the "url" tag in BibTeX creates a nice link. But I would highly recommend requiring the URL to be "https://dx.doi.org/10.XXXX/YYYYY" as opposed to the publisher's proprietary link (which will change).

Conversey, using the "doi" tag in BibTeX creates a doi entry in the reference, but it is not a hyperlink that actually works (for any of the PDF viewers I've tested it with).

"doi" seems to be a better choice from a citation / reference cataloging POV, but the link is useless. Using both seems duplicative.

Thoughts?

**Comment by HaoZeke** [comment]
DOI is generally cleaner.. URL's sort of stand out too much.
Plus web browsers handle doi links well. So pdf viewers not opening it directly is usually not a problem...

**Comment by dwsideriusNIST** [comment]
Alternative: the BibTeX style could be hacked to use the "doi" tag but include the "https://dx.doi.org/" prefix in the URL. The link works and we get a clean reference.

**Comment by HaoZeke** [comment]
That sounds great!

Something like this maybe?

```tex
\newbibmacro{string+doiurlisbn}[1]{%
  \iffieldundef{doi}{%
    \iffieldundef{url}{%
      \iffieldundef{isbn}{%
        \iffieldundef{issn}{%
          #1%
        }{%
          \href{http://books.google.com/books?vid=ISSN\thefield{issn}}{#1}%
        }%
      }{%
        \href{http://books.google.com/books?vid=ISBN\thefield{isbn}}{#1}%
      }%
    }{%
      \href{\thefield{url}}{#1}%
    }%
  }{%
    \href{https://doi.org/\thefield{doi}}{#1}%
  }%
}

\DeclareFieldFormat{journaltitle}{\usebibmacro{string+doiurlisbn}{\mkbibemph{#1}}}
```

And coupled with this (for poorly formatted .bib files):

```tex
\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
      \step[ % removes http://dx.doi.org/ string from doi field
        fieldsource=doi,
        match=\regexp{https?://(dx.)?doi.org/(.+)},
        replace=\regexp{$2}
      ]
    }
  }
}
```

The above is mostly from the [tex stackexchange](https://tex.stackexchange.com/questions/342876/how-to-cut-out-a-prefix-in-the-doi-field-if-present) but I'd be happy to look into a pull request too. A working MWE is attached.

[tes.txt](https://github.com/livecomsjournal/article_templates/files/1868301/tes.txt)

**Comment by dwsideriusNIST** [comment]
I'll test these in a modified BST file. I found a quick hack, but your solution looks more complete.

**Comment by davidlmobley** [comment]
I like the idea of including these as DOI links like you guys are proposing, assuming this can be done without the users having to know about what's going on under the hood.

**Comment by dwsideriusNIST** [comment]
@davidlmobley and @HaoZeke: I looked into this a little more closely and we can make a very simple change to the BST file to make the DOIs proper links. It is a one-line fix. Here is my thought:

1. State a preference for DOI-based links rather than publisher-specific URLs.
2. Only accept publisher URLs if a DOI does not exist (e.g., this comes up for a "Mathematische Annalen" citation in the Sampling-uncertainty paper).
3. Because we have to allow actual URLs in some situations, the BST file cannot just ignore URLs carte blanche. So, the author has to set up the .BIB file correctly: include DOIs if available and include URLs otherwise.
4. In a related note, the bibliography should not contain extraneous comments or other identifiers (PUBMED); this requires the author to strip those BibTeX keys out of their entries.

We'll have to put a note about this in the author guide. The alternative is a much more complicated BST file (maybe even something in the document TeX, I'm not sure) that filters out URLs in favor of DOIs and would probably fail in some odd circumstance that we've not considered.

**Comment by HaoZeke** [comment]
Well it's true that the best fix is one which the users implement instead of an in place bib rewrite.

**Comment by davidlmobley** [comment]
This plan sounds good to me, @dwsideriusNIST . Up for making the requisite changes (or at least PRs to do them)?

**Comment by dwsideriusNIST** [comment]
@davidlmobley I'll have a PR in shortly.

**Comment by dwsideriusNIST** [comment]
I've renamed this issue since it needs to be broadened past the DOI/URL issue.

I'm returning to this issue due to experience gained with the Sampling-Uncertainty paper. Basically, we should perform a review of the reference formats in a paper close to "live" status. The default BST file is creating a rather verbose entries in the bibliography. For example, it includes the issue number in addition to volume (if included); also, it will include extraneous information like "month" if that is included in the BIB file. I think the issue is that the BST file that we started with differs quite a bit from a standard physics/chemistry style bibliographic format.

Also, is there a way to error check the bibliography? Say, in the way that ACS or APS does for papers in the proofing stage? One observation for me based on this process is that I now really appreciate the corrections / error correcting that publishers do in the bibliography. It's taken multiple iterations to correct and update the BibTeX file for the Sampling-Uncertainty paper that was assembled piecemeal by each of the authors.

**Comment by davidlmobley** [comment]
I do not know a way to error-check the bibliography. Let me ask Twitter. 

I wonder if we should also update the BST to remove extraneous information like month. Thoughts @dwsideriusNIST ? 

Should we also perhaps add something on this in the instructions for authors AND for reviewers -- to pay attention to consistency in bibliography formatting?

**Comment by mrshirts** [comment]
Hopefully, some of the bibliography will be checked by people over the
lifetime of the document versions :)

**Comment by davidlmobley** [comment]
Hmm, I had in my head it already did link the DOIs, but I must be remembering wrong.

No news on error checking bibliographies from twitter yet except one guy who says he's working on something using the Mendeley API and will share it when it's done.

Agree re excluding month. Is that trivial in the BST? If so I could try to do it.

**Comment by mrshirts** [comment]
It's not trivial; bst's are a whole separate language.   You have to recreate the bst (there are a few tools for this); at least that's what I've done in the past.  I usually just strip the month out of the .bib file when exporting, but we want something that works with random persons bst's. 

But maybe Dan S. knows how to fix the bst directly?

**Comment by davidlmobley** [comment]
The Twitter guy produced some kind of a draft already, using CrossRef. Haven't tried yet (though I will at some point) but posting here for posterity or in case @dwsideriusNIST wants to try: https://github.com/jaimergp/fixbibtex

**Comment by dwsideriusNIST** [comment]
This is a mop-up reply:
1. The as-is BST file already creates clickable links for either or both of the "doi" and "url" fields. The article formatting instructions tell the authors to use DOI as first preference and URL only as a fall-back in case a DOI is not available.
2. I'll take a look at excluding the month. Probably not difficult, unless it's being supplied by NATBIB or something else.
3. I'll look at the reference checker.

**Comment by dwsideriusNIST** [comment]
Regarding the exclusion/suppress of the month, we need help. I poked around the BST file but wasn't able to both 1) preserve the current ordering of bibliographic elements and 2) suppress the month. (I found how to suppress the month, but then the year was moved ahead of the journal title. Not desirable.)

Can we ask @liantze to help with this?

**Comment by dwsideriusNIST** [comment]
The fixbibtex script is sort of helpful. It did find one DOI that was missing in the Sampling-Uncertainty paper, but it made a lot of, err, suggested changes that were junk. Maybe iterate on it...

**Comment by davidlmobley** [comment]
@dwsideriusNIST - maybe reach out to the author on a test case on his GitHub issue tracker? Or send me your test case and I can do it.

@liantze are you able to help with suppressing the month in the BST file?

**Comment by dwsideriusNIST** [comment]
@davidlmobley I submitted an issue in his repo and included an example bibtex file that triggers the errors.

If we start suggesting that automated tools to fix their bibtex files, we're going to run into an old problem - the DOI vs URL issue. (Short version: a tool like https://github.com/jaimergp/fixbibtex will add URLs that are missing. The BST file in current form will include both URL and DOI if both are in the BibTeX entry.) The BST file will need a fix, along the lines of:

IF (DOI = present):
    -> insert DOI as clickable link (add https://dx.doi.org, etc., to the link)
    -> Don't include URL
ELSEIF(URL = present):
    -> insert URL as clickable link
ELSE:
    -> Don't create a clickable link

Again, this will require help from someone like @liantze

**Comment by dwsideriusNIST** [comment]
Turns out the if/then sequence described above was really easy to code in the BST file. My fork is way ahead of the master, though, so I won't commit it until later.

**Comment by dwsideriusNIST** [comment]
OK, after way too much fiddling, I found a BST modification that suppresses the month. I have to decide how to commit all these changes, because they're all in my fork of the article_templates repo and the PR to change to the class file hasn't been approved yet. I'll be back soon.

**Comment by davidlmobley** [comment]
@dwsideriusNIST - excellent. What do we need to do to get back in sync?

**Comment by dwsideriusNIST** [comment]
I'm closing this issue thread; we can reopen it if another aspect of the bibliography crops up.
