### ISSUE TITLE
Formatting at time of publication (DOI, volume, etc.)?

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/article_templates#55]
Will the official version of a LiveCoMS paper have some branding and/or volume information in the header/footer/somewhere? Perhaps added by Scholastica? There should be some indication of how to cite the article.

**Comment by dwsideriusNIST** [comment]
Bump

**Comment by mrshirts** [comment]
Good question.  It will appear on the website with all the metadata/branding volume information, but it's not clear how to have the PDF have the information as well.  We'll have to think about that.

**Comment by davidlmobley** [comment]
Seems like this is something we can ask Scholastica, @mrshirts , though I would assume they are not going to be processing our PDFs to add anything to them, so they will probably say, "Well, that's your concern."

Assuming they are not helpful, what about:
a) We add something to the LaTeX templates that says "for citation details, visit (url)" and give the URL of the main README.md for their github repo
b) Upon publication we have them update the README.md of their GitHub repo to give citation details

That's not ideal though; better would be to have the citation details in the PDF itself.

*What if we made this the last step in the review process?* Specifically, once we accept the article, we assign it to an "issue" and give it "page numbers" and then we (or they) can do a PR to a branch of their article which adds these to a header (?) of the article and generates a final PDF for publication. Then we do another PR to remove these so they can make subsequent updates to the article without carrying out volume/page numbers.

**Comment by mrshirts** [comment]
I think the "last step in review" is decent.  If we set up the template right, we could have a boolean that says whether it is for publication or not, and what the issue/volum number is.  Editors could even submit it as a PR themselves.

**Comment by dwsideriusNIST** [comment]
I agree with the "last step in review" approach - a few variables and a macro should cover the TeX apart from the changes in the template.

**Comment by davidlmobley** [comment]
Is this something you're able to do @dwsideriusNIST ?

**Comment by dwsideriusNIST** [comment]
I can write the TeX variables and macros first and just use a placeholder text somewhere in the frontmatter to debug it.

For modifications to the template, we'll need to first decide where/how to put the issue/page/DOI info [I would suggess KISS, replicate something like ACS or AIP] and then probably need help from @liantze or someone with similar skills.

**Comment by dwsideriusNIST** [comment]
How about an option like this:

[main.pdf](https://github.com/livecomsjournal/article_templates/files/2098583/main.pdf)

Check the footer of any of the pages.

Question: since there is no print version, are articles assigned an article number (like JCP) or a page identifier. Followup question: if there is an article number, is it part of the DOI? (the class macro could build the DOI from the article number if the relationship is deterministic.)

**Comment by mrshirts** [comment]
Good question about DOI.  I will check with CU Libraries about how we will assign them - the decided they would pay the subscription, but we didn't work out how we would do the logistics of assigning.

**Comment by davidlmobley** [comment]
I like that look, @dwsideriusNIST .

**Comment by dwsideriusNIST** [comment]
Here's a minor update, making the DOI a clickable link.

[main.pdf](https://github.com/livecomsjournal/article_templates/files/2106084/main.pdf)

I'll await an answer from @mrshirts regarding the DOI and article number before submitting a PR. The code is pretty straightforward, so the final modifications will not be difficult.

**Comment by mrshirts** [comment]
I talked to my library contact; CU procurement (as anticipated) is still dragging out the process of the contract with CrossRef, so we still don't know the exact details of DOI numbering.  We will have our own root DOI, for the journal, but I don't know how the numbers are generated.  I think worst case scenario, we just plug in the number as a PR.  That may be part of the editorial process; we (one of the editors) creates a branch with the necessary modifications that they can generate the final PDF.  

My imagination is that we are going to be only dealing with 5-10 new papers each month (filtering out a lot at the pre-submission letter level), so this level of work will not be too hard to handle.

**Comment by davidlmobley** [comment]
@dwsideriusNIST that looks really elegant and nice. :+1:

**Comment by dwsideriusNIST** [comment]
@davidlmobley Thanks, the updated code is in PR #56
