### ISSUE TITLE
How to include version number in the title of articles

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/article_templates#60]
It seems like it might make most sense to define the version in some \newcommand and have that automatically filled in in the title (and other places) with the right formatting.  There is significant inconsistency in how the version is being included so far, so coming up with a consistent choice (such as "Best Practices Paper: v1")  

Other thoughts on this?

**Comment by jalemkul** [comment]
Would it be worthwhile to be slightly more verbose such that it's clear that the version is for the article itself? Doing something like "Title of Paper: Article v1.0" would probably be an easy disambiguation, e.g. for my article.

**Comment by davidlmobley** [comment]
I like that idea, @jalemkul . @mrshirts ? @dmzuckerman @dwsideriusNIST ? @hmayes ?

**Comment by dmzuckerman** [comment]
Minor problem is that many articles have a colon.  Are we ok with two colons?  An alternative would be parentheses "Title of Paper (Article v1.0)" or brackets [ ] or braces { }.  Not many titles with braces in them!

**Comment by davidlmobley** [comment]
Ah, excellent point. I wonder if braces/brackets will play OK with bib files and Google Scholar, etc.? I would tend to be inclined towards parens for that reason.

**Comment by mrshirts** [comment]
Brackets might probably be OK: Search for benzo[alpha]pyrene in google scholar. https://scholar.google.com/scholar?hl=en&as_sdt=0%2C6&q=benzo%5Balpha%5Dpyrene&btnG=

**Comment by davidlmobley** [comment]
What about with bibtex?

**Comment by mrshirts** [comment]
I tried in one file, and there were no problems; no errors or warnings, showed up correctly.   Need to try in the template, have to head out now, will try soon.

That doesn't guarantee it DOES work, just that its likely to work in general.

**Comment by mrshirts** [comment]
It works OK in bibtex in the LiveCoMS latex template as well. 

One note with Google scholar is that titles that have `benzo[alpha]pyrene` are changed to `benzo [alpha] pyrene` (extra spaces before and after the brackets).  That probably isn't an issue for us, since we will put a space before the bracket.

**Comment by davidlmobley** [comment]
OK, so I'd go for brackets then.

**Comment by mrshirts** [comment]
So the conclusion is that the title would be "Title of Paper [Article v1.0]"? Do we want 'article' in the title? Would "Title of Paper [v1.0]" be better?

**Comment by jalemkul** [comment]
Omitting the word "Article" then reverts us back to @dmzuckerman's initial observation about my article's title being confusing. If one supplies a software version in the title, then "v1.0" gets confusing. If one then omits the software version and the only "version" remaining is the article itself, then the title could even be considered incorrect, e.g. if I wrote "A Suite of Tutorials for the GROMACS Simulation Package [v1.0]" I would say that is just flat-out wrong, because there was never such a released GROMACS version.

**Comment by mrshirts** [comment]
OK, I'm fine with [Article v1.0].  I've put that in the letters to two other people now.  Probably we should put that in the template.

**Comment by davidlmobley** [comment]
Yes, agree with the `[Article v1.0]` point.

Presumably we need to actually update the templates with that info. Do you want to do this, @mrshirts , or shall I?

**Comment by davidlmobley** [comment]
Ah, resolved by #63 .
