### ISSUE TITLE
Bolding of Editor names, no author names

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/article_templates#64]
This was a lingering issue in the Sampling-Uncertainty paper, but it's cropped up in the TransportChecklist paper too.

Basically, if there is a reference with editors, but no authors, the first editor's name should be bolded to be consistent with the rest of the references. E.G., see refs 20 and 50 in https://github.com/dmzuckerman/Sampling-Uncertainty/blob/c38f4fb567ba249fd479f4aed36e1a966b608ff7/main.pdf

I found how to bold the first editor's names, but then it bolded the editor name when there are authors as well (e.g., ref. 43 in the same PDF above).

**Comment by dwsideriusNIST** [comment]
Fix proposed in PR #80

**Comment by davidlmobley** [comment]
Merged.
