### ISSUE TITLE
List of things to fix/adjust before issue 1 published (we will ask for people to redo the templates then).

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/article_templates#70]
1. Sometimes, the link to the GitHub repository in the PDF isn't working.  See https://www.livecomsjournal.org/article/5965-introduction-to-markov-state-modeling-with-the-pyemma-software-article-v1-0
2. Figure out ORCID iD placement.

**Comment by mrshirts** [comment]
Add to the above as we go.

**Comment by davidlmobley** [comment]
If we can auto-add the `https://` prefix that'd certainly be a time-saver.

**Comment by dwsideriusNIST** [comment]
> If we can auto-add the `https://` prefix that'd certainly be a time-saver.

Upon revisiting the macro... it's not a macro, just a variable definition in the manuscript preamble. We can make it a macro if you _really_ want to go down that road.

**Comment by davidlmobley** [comment]
Not sure how difficult that is. If it's easy, then I'd go for it but if it's going to take a pretty significant investment of time then I'd just make sure we check this...

In other words, how quick is the return on investment?

**Comment by davidlmobley** [comment]
@mrshirts can you not use the "assigned" tab unless the person is actually going to DO it and has agreed to do so? Sometimes I use the "assigned" thing as a tasks list for myself. 

It works better, if you want feedback on something, to just tag me in the issue tracker (or if it is a PR, request a review from me). But in my mind "assigned" means a very specific thing: I'm the one responsible for completing the referenced task.

**Comment by mrshirts** [comment]
@davidlmobley  OK sounds good.

**Comment by dwsideriusNIST** [comment]
> Not sure how difficult that is. If it's easy, then I'd go for it but if it's going to take a pretty significant investment of time then I'd just make sure we check this...
> 
> In other words, how quick is the return on investment?

I came up with a quick macro that adds the URL prefix to a github repo name if it is missing, but then realized that it would be about impossible to error check all the ways an author could garble the URL by entering the repo name incorrectly. Ultimately, the repo name has to be typed correctly, which is no different than just entering the URL properly in the first place. Thus, I would vote for no macro, just the preamble variable definition.

**Comment by dwsideriusNIST** [comment]
OK, thanks, I'll put in a PR to the pyEMMA paper with a fix to their github URL

**Comment by mrshirts** [comment]
Or let them do it.  They are aware now.

**Comment by dwsideriusNIST** [comment]
PR is already in, it's doing an automatic circleCI check.

**Comment by dwsideriusNIST** [comment]
Is the ACS-style ORCID list OK for you all? I can settle on the formatting if you're happy with it.

@davidlmobley put out a request to @liantze to see if we can make the orcid macro more sophisticated, otherwise the macro just include duplicate info.

As for alternative author IDs, I wrote the macro in a way that it could be repurposed for other author IDs in case that is ever needed.

**Comment by dmzuckerman** [comment]
I'm OK with what @dwsideriusNIST has done.  If we can get something fancier in time, that would be nice, but the main thing is to have the numbers.

**Comment by dwsideriusNIST** [comment]
OK, I'll put in a PR with the simple macro and updates to the templates. We can change the livecoms class file in the future if we figure out how to pull author names directly from the \author macros. It won't change the output, just the macro syntax.

At some point we'll need authors of the already-published papers to update their CLS and BST files, then recompile.

**Comment by dwsideriusNIST** [comment]
See PR #71

**Comment by dwsideriusNIST** [comment]
This is an attempt to triage the remaining to-do items for the template:

1a. Approve final form of footer; specifying "ASAP" or actual citation info.
1b. Author instructions for activating the publication footer
   
2a. Finalize Author identifiers / ORCID. Based on PR https://github.com/livecomsjournal/livecomsjournal.github.io/pull/173 for the github.io site, it seems that a simple macro is best at present. PR #71 provides working code
2b. Author instructions

3. Finalize guidelines for versioning. See https://github.com/livecomsjournal/livecomsjournal.github.io/issues/176

**Comment by davidlmobley** [comment]
I agree with that ordering, @dwsideriusNIST .

**Comment by dwsideriusNIST** [comment]
OK, watch for a sequence of PRs to address these items.

**Comment by dwsideriusNIST** [comment]
See PR #72

**Comment by dwsideriusNIST** [comment]
This issue tracker can be closed.
