### ISSUE TITLE
Issue number

### ISSUE THREAD

**Issue by ramess101** [livecomsjournal/article_templates#73]
@dwsideriusNIST 

I apologize for the naming of this issue, but I couldn't resist opening Pandora's box.

During the "Upon Acceptance" stage, I entered the information required for the pubversion option. However, I noticed that there was not a parameter for the Issue number, i.e., \pubissue or \issuenum. I asked @mrshirts and he suggested that I post an issue on GitHub for @dwsideriusNIST. So that is what I am doing.

**Comment by mrshirts** [comment]
issueception!

**Comment by dwsideriusNIST** [comment]
No problem... actually quite easy to fix. Just add:

`\pubissue{1}`

to the block containing `\pubvolume`, `\pubyear`, etc., then recompile.

I did not update the "Upon Acceptance" instructions after we decided to include the issue number in the footer citation. That will be corrected in a few minutes.

**Comment by dwsideriusNIST** [comment]
See: https://github.com/livecomsjournal/livecomsjournal.github.io/pull/178

**Comment by ramess101** [comment]
@dwsideriusNIST 

Thanks for the quick reply. OK, maybe I need to update my template (current version was pulled on October 9th, 2018) because I tried including \pubissue and it would not compile.

**Comment by dwsideriusNIST** [comment]
Yes, good catch. Sync up your CLS and BST files with the latest commit from the templates repo and then it should compile. If not, let me know and I'll pull your repo to test it locally.

**Comment by dwsideriusNIST** [comment]
Also FYI, you'll need to update the template files in the near future; there is a pending PR (#72) that provides the (hopefully) final updates prior to issue 1 being released.

Lastly, you'll need to add ORCIDs to the manuscript (see #72 for instructions). You may have to pester co-authors to collect them or to request that they obtain one in the first place.

**Comment by ramess101** [comment]
@dwsideriusNIST 

OK, I will let you know if I have any further challenges with the template.

As for the ORCIDs, fortunately I have already pestered each of my co-authors. So we should be good there.

**Comment by ramess101** [comment]
@dwsideriusNIST 

Thanks again for your help. The manuscript now displays the issue number and has the "Author Information" section with each author's ORCID. 

I think we can close "Issue Number" #73

**Comment by dwsideriusNIST** [comment]
Would one of the admins close this issue?
